# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT

name: Setup Node.js and Install Dependencies
description: Installs Node.js with version pinning and runs npm ci to install project dependencies.

inputs:
  node-version:
    description: Node.js version to install
    required: false
    default: '20'
  cache:
    description: Package manager cache to use
    required: false
    default: 'npm'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v4.1.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

    - name: Install dependencies
      shell: pwsh
      run: npm ci
