workflow:
  name: isaaclab-inline-training
  timeout:
    exec_timeout: 23h
  resources:
    default:
      gpu: 1
      cpu: 8
      memory: 48Gi
      storage: 80Gi
  tasks:
    - name: isaac-training
      image: "{{ image }}"
      command:
        - /bin/bash
        - /tmp/entry.sh
      environment:
        TASK: "{{ task }}"
        NUM_ENVS: "{{ num_envs }}"
        MAX_ITERATIONS: "{{ max_iterations }}"
        ACCEPT_EULA: "Y"
        PRIVACY_CONSENT: "Y"
        ENCODED_ARCHIVE: "{{ encoded_archive }}"
        PAYLOAD_ROOT: "{{ payload_root }}"
        SLEEP_AFTER_UNPACK: "{{ sleep_after_unpack }}"
        AZURE_SUBSCRIPTION_ID: "{{ azure_subscription_id }}"
        AZURE_RESOURCE_GROUP: "{{ azure_resource_group }}"
        AZUREML_WORKSPACE_NAME: "{{ azure_workspace_name }}"
        AZURE_AUTHORITY_HOST: "{{ azure_authority_host }}"
        MLFLOW_TRACKING_TOKEN_REFRESH_RETRIES: "{{ mlflow_token_refresh_retries }}"
        MLFLOW_HTTP_REQUEST_TIMEOUT: "{{ mlflow_http_request_timeout }}"
        RUN_AZURE_SMOKE_TEST: "{{ run_azure_smoke_test }}"
        PYTHON: "{{ python }}"
        CHECKPOINT_URI: "{{ checkpoint_uri }}"
        CHECKPOINT_MODE: "{{ checkpoint_mode }}"
        REGISTER_CHECKPOINT: "{{ register_checkpoint }}"
        TRAINING_BACKEND: "{{ training_backend }}"
      files:
        - path: /tmp/entry.sh
          contents: |
            #!/bin/bash
            set -euo pipefail

            if [[ -z "${ENCODED_ARCHIVE:-}" ]]; then
              echo "encoded_archive is required" >&2
              exit 1
            fi

            ARCHIVE_PATH="${TEMP_ARCHIVE:-/tmp/isaac_payload.zip}"
            PAYLOAD_ROOT="${PAYLOAD_ROOT:-/workspace/isaac_payload}"
            TRAINING_ROOT="${TRAINING_ROOT:-${PAYLOAD_ROOT}/src/training}"

            python_cmd_raw="${PYTHON:-python}"
            read -r -a python_cmd <<< "${python_cmd_raw}"
            python_exec="/isaac-sim/kit/python/bin/python3"
            if [[ ! -x "${python_exec}" ]]; then
              python_exec="${python_cmd[0]}"
            fi
            configure_uv() {
              local resolved_env
              if ! command -v uv &>/dev/null; then
                return 0
              fi
              if [[ -n "${python_exec}" ]]; then
                resolved_env="$("${python_cmd[@]}" -c 'import sys; print(sys.prefix)' 2>/dev/null || true)"
                export UV_PYTHON="${python_exec}"
                if [[ -n "${resolved_env}" && -d "${resolved_env}" ]]; then
                  export UV_PROJECT_ENVIRONMENT="${resolved_env}"
                  echo "uv configured with Python: ${python_exec}, environment: ${resolved_env}"
                else
                  echo "uv configured with Python: ${python_exec}"
                fi
              else
                echo "Python executable not set; uv will use system discovery"
              fi
            }
            run_python() {
              if [[ -n "${python_exec}" ]]; then
                "${python_exec}" "$@"
              else
                "${python_cmd[@]}" "$@"
              fi
            }

            mkdir -p "${PAYLOAD_ROOT}"
            printf '%s' "${ENCODED_ARCHIVE}" | base64 -d > "${ARCHIVE_PATH}"
            unzip -oq "${ARCHIVE_PATH}" -d "${PAYLOAD_ROOT}"

            if [[ -n "${SLEEP_AFTER_UNPACK:-}" ]]; then
              echo "SLEEP_AFTER_UNPACK set; sleeping for ${SLEEP_AFTER_UNPACK} after payload unpack"
              sleep "${SLEEP_AFTER_UNPACK}"
              echo "Finished post-unpack sleep; exiting"
              exit 0
            fi

            # Install uv for faster package management (standalone installer is more reliable)
            if ! command -v uv &>/dev/null; then
              echo "Installing uv package manager..."
              if curl -LsSf https://astral.sh/uv/install.sh | sh 2>/dev/null; then
                export PATH="${HOME}/.local/bin:${PATH}"
              fi
            fi
            # Configure uv for Isaac Lab's embedded Python environment
            configure_uv

            export PYTHONPATH="/isaac-sim/exts/omni.pip.compute/pip_prebundle:${TRAINING_ROOT}:${PYTHONPATH:-}"

            # Keep Isaac Sim prebundled SciPy; pin numpy<2
            echo "Ensuring Isaac Sim prebundled scipy is used..."
            if command -v uv &>/dev/null && [[ -n "${UV_PYTHON:-}" ]]; then
              uv pip uninstall -y scipy >/dev/null 2>&1 || true
              uv pip install --upgrade "numpy>=1.26.0,<2.0.0" || {
                echo "uv failed, falling back to pip..."
                run_python -m pip install --upgrade "numpy>=1.26.0,<2.0.0" --quiet
              }
            else
              run_python -m pip uninstall -y scipy >/dev/null 2>&1 || true
              run_python -m pip install --upgrade "numpy>=1.26.0,<2.0.0" --quiet
            fi

            MODE="train"
            if [[ "${RUN_AZURE_SMOKE_TEST:-0}" == "1" ]]; then
              MODE="smoke-test"
            fi

            train_args=(
              --mode "${MODE}"
              --task "${TASK:-}"
              --num_envs "${NUM_ENVS:-}"
              --max_iterations "${MAX_ITERATIONS:-}"
              --checkpoint-uri "${CHECKPOINT_URI:-}"
              --checkpoint-mode "${CHECKPOINT_MODE:-from-scratch}"
              --register-checkpoint "${REGISTER_CHECKPOINT:-}"
              --headless
            )

            bash "${TRAINING_ROOT}/scripts/train.sh" "${train_args[@]}"

default-values:
  image: nvcr.io/nvidia/isaac-lab:2.2.0
  task: Isaac-Velocity-Rough-Anymal-C-v0
  num_envs: "2048"
  max_iterations: ""
  encoded_archive: ""
  payload_root: /workspace/isaac_payload
  sleep_after_unpack: ""
  azure_subscription_id: ""
  azure_resource_group: ""
  azure_workspace_name: ""
  azure_authority_host: https://login.microsoftonline.com
  mlflow_token_refresh_retries: "3"
  mlflow_http_request_timeout: "60"
  python: "/workspace/isaaclab/isaaclab.sh -p"
  run_azure_smoke_test: "0"
  checkpoint_uri: ""
  checkpoint_mode: "from-scratch"
  register_checkpoint: ""
  training_backend: "skrl"

