workflow:
  name: isaaclab-dataset-training
  timeout:
    exec_timeout: 23h
  resources:
    default:
      gpu: {{ gpu }}
      cpu: {{ cpu }}
      memory: {{ memory }}
      storage: {{ storage }}
  tasks:
    - name: isaac-training
      image: "{{ image }}"
      command:
        - /bin/bash
        - /tmp/entry.sh
      environment:
        NVIDIA_DRIVER_CAPABILITIES: "all"
        TASK: "{{ task }}"
        NUM_ENVS: "{{ num_envs }}"
        MAX_ITERATIONS: "{{ max_iterations }}"
        ACCEPT_EULA: "Y"
        PRIVACY_CONSENT: "Y"
        TRAINING_ROOT: "{{input:0}}/{{ dataset_name }}/training"
        AZURE_SUBSCRIPTION_ID: "{{ azure_subscription_id }}"
        AZURE_RESOURCE_GROUP: "{{ azure_resource_group }}"
        AZUREML_WORKSPACE_NAME: "{{ azure_workspace_name }}"
        AZURE_AUTHORITY_HOST: "{{ azure_authority_host }}"
        MLFLOW_TRACKING_TOKEN_REFRESH_RETRIES: "{{ mlflow_token_refresh_retries }}"
        MLFLOW_HTTP_REQUEST_TIMEOUT: "{{ mlflow_http_request_timeout }}"
        RUN_AZURE_SMOKE_TEST: "{{ run_azure_smoke_test }}"
        PYTHON: "{{ python }}"
        CHECKPOINT_URI: "{{ checkpoint_uri }}"
        CHECKPOINT_MODE: "{{ checkpoint_mode }}"
        REGISTER_CHECKPOINT: "{{ register_checkpoint }}"
        TRAINING_BACKEND: "{{ training_backend }}"
      inputs:
        - dataset:
            name: "{{ dataset_bucket }}/{{ dataset_name }}"
            localpath: "{{ training_localpath }}"
      files:
        - path: /tmp/entry.sh
          contents: |
            #!/bin/bash
            set -euo pipefail

            TRAINING_ROOT="${TRAINING_ROOT:-{{input:0}}/training-code/training}"

            if [[ ! -d "${TRAINING_ROOT}" ]]; then
              echo "Error: Training root not found at ${TRAINING_ROOT}" >&2
              echo "Contents of {{input:0}}:" >&2
              ls -la "{{input:0}}/" || true
              exit 1
            fi

            echo "Training folder mounted at: ${TRAINING_ROOT}"
            ls -la "${TRAINING_ROOT}"

            export PYTHONPATH="${TRAINING_ROOT}:${PYTHONPATH:-}"

            MODE="train"
            if [[ "${RUN_AZURE_SMOKE_TEST:-0}" == "1" ]]; then
              MODE="smoke-test"
            fi

            train_args=(
              --mode "${MODE}"
              --task "${TASK:-}"
              --num_envs "${NUM_ENVS:-}"
              --max_iterations "${MAX_ITERATIONS:-}"
              --checkpoint-uri "${CHECKPOINT_URI:-}"
              --checkpoint-mode "${CHECKPOINT_MODE:-from-scratch}"
              --register-checkpoint "${REGISTER_CHECKPOINT:-}"
              --headless
            )

            bash "${TRAINING_ROOT}/scripts/train.sh" "${train_args[@]}"

default-values:
  image: nvcr.io/nvidia/isaac-lab:2.3.2
  task: Isaac-Velocity-Rough-Anymal-C-v0
  num_envs: "2048"
  max_iterations: ""
  dataset_bucket: training
  dataset_name: training-code
  training_localpath: ""
  azure_subscription_id: ""
  azure_resource_group: ""
  azure_workspace_name: ""
  azure_authority_host: https://login.microsoftonline.com
  mlflow_token_refresh_retries: "3"
  mlflow_http_request_timeout: "60"
  python: "/workspace/isaaclab/isaaclab.sh -p"
  run_azure_smoke_test: "0"
  checkpoint_uri: ""
  checkpoint_mode: "from-scratch"
  register_checkpoint: ""
  training_backend: "skrl"
  gpu: "1"
  cpu: "30"
  memory: 400Gi
  storage: 200Gi

