name: 📚 Documentation
description: Report documentation issues or request improvements
title: "docs: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Title format**: `docs: Brief description` or `docs(scope): Brief description`
        **Scopes**: deploy, training, workflows, README
  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Which file or section has the issue?
      placeholder: "README.md, docs/mlflow-integration.md, etc."
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong or missing?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: How should the documentation be improved?
    validations:
      required: false
